[versions]
# https://github.com/JetBrains/compose-jb/blob/master/VERSIONING.md#kotlin-compatibility
kotlin = "1.8.0" # https://kotlinlang.org/docs/releases.html#release-details
agp = "7.4.0-beta02" # https://developer.android.com/studio/releases/gradle-plugin
compose = "1.3.0" # https://github.com/JetBrains/compose-jb

coreKtx = "1.9.0" # https://developer.android.com/jetpack/androidx/releases/core
appcompat = "1.6.1" # https://developer.android.com/jetpack/androidx/releases/appcompat
activity = "1.6.1" # https://developer.android.com/jetpack/androidx/releases/activity

compileSdk = "33"
minSdk = "24"
targetSdk = "33"

koin-version = "3.3.3"
koin-compose-version = "3.4.2"


[libraries]
androidGradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
composeGradle = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose" }
kotlinGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

androidx-coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }

koin-core = {module = "io.insert-koin:koin-core", version.ref = "koin-version"}
koin-compose = {module = "io.insert-koin:koin-androidx-compose", version.ref = "koin-compose-version"}

junit = "junit:junit:4.13.2"